server:
  port: 8080  servlet:
    context-path: /
    encoding:      charset: UTF-8      enabled: true      force: true

spring:
  mvc:
    view:
      # jsp 설정
      prefix: /WEB-INF/view/
      suffix: .jsp
  # 자동 새로고침
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring
    username: postgres
    password: root

rest:
  server-url: http://localhost:8080/rest